version: '3.8'

services:
  bot-farm:
    build: .
    container_name: workers-bot
    environment:
      - DATABASE_URL=postgresql://workers:S3cureP%40ssw0rd2025%21@host.docker.internal:5544/workersdb
    volumes:
      - ./logs:/app/logs
      - ./sessions:/app/sessions
    restart: unless-stopped
